services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: netwrkdb
    environment:
      POSTGRES_DB: netwrkdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d netwrkdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netwrk-app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./lambda/app:/app/app
      - ./lambda/integration_tests:/app/integration_tests
    stdin_open: true
    tty: true
