version = 0.1

[default.deploy.parameters]
stack_name = "netwrk-backend"
resolve_s3 = true
s3_prefix = "netwrk-backend"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ImageUri=\"711387105820.dkr.ecr.us-east-2.amazonaws.com/netwrk-backend:latest\" DomainName=\"api.mynetwrk.com\" CertificateArn=\"arn:aws:acm:us-east-2:711387105820:certificate/62eb2802-6279-4e11-a439-e3bcf6c4a9e5\" S3BucketName=\"netwrkbucket\""
image_repositories = []

[default.global.parameters]
region = "us-east-2"
